/**
 * mill format: yaml
 *
 * Converts compilation.json to YAML output.
 * Simple JSON-to-YAML serializer — handles objects, arrays, strings,
 * numbers, booleans, and nulls. No external dependencies.
 * Zero dependencies — node built-in only.
 */

export const name = "yaml";
export const extension = ".yaml";
export const mimeType = "text/yaml; charset=utf-8";
export const description = "YAML serialization of compilation data";

/**
 * Convert a compilation object to YAML.
 * @param {object} compilation - The compilation.json content
 * @returns {string} YAML output
 */
export function convert(compilation) {
  const lines = [];
  lines.push("# Auto-generated by mill yaml format");
  lines.push("");
  lines.push(toYaml(compilation, 0));
  return lines.join("\n");
}

function toYaml(value, indent) {
  const pad = " ".repeat(indent);
  if (Array.isArray(value) && value.length) {
    return value
      .map((item) =>
        isContainer(item)
          ? `${pad}-\n${toYaml(item, indent + 2)}`
          : `${pad}- ${scalar(item)}`,
      )
      .join("\n");
  }
  if (
    value &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    Object.keys(value).length
  ) {
    return Object.entries(value)
      .map(([key, item]) =>
        isContainer(item)
          ? `${pad}${scalar(key)}:\n${toYaml(item, indent + 2)}`
          : `${pad}${scalar(key)}: ${scalar(item)}`,
      )
      .join("\n");
  }
  return pad + scalar(value);
}

function isContainer(value) {
  return value && typeof value === "object" && Object.keys(value).length > 0;
}

function scalar(value) {
  return JSON.stringify(value ?? null).replace(
    /[\u0085\u2028\u2029]/g,
    (char) => `\\u${char.charCodeAt(0).toString(16).padStart(4, "0")}`,
  );
}
