/**
 * confluence-sync.js -- Publish sprint data to Confluence via the Atlassian MCP pattern.
 *
 * Reads compilation.json (never claims.json directly) and publishes to Confluence.
 * Creates a parent page per sprint, with child pages for claims table + brief.
 * Dual-format pages: human-readable table at top, collapsed JSON code block at bottom.
 * Tracks sync state in .wheat/sync-state.json.
 * Label lifecycle: wheat-active on publish, wheat-archived on sprint close.
 *
 * Zero dependencies -- uses only Node.js built-ins + Atlassian MCP tool calls.
 */

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

// ── Sync state persistence ──────────────────────────────────────────────────

/**
 * Load sync state from .wheat/sync-state.json.
 * Returns an object keyed by sprint slug.
 */
export function loadSyncState(wheatRoot) {
  const statePath = path.join(wheatRoot, "sync-state.json");
  if (fs.existsSync(statePath)) {
    return JSON.parse(fs.readFileSync(statePath, "utf8"));
  }
  return {};
}

/**
 * Persist sync state to .wheat/sync-state.json.
 */
export function saveSyncState(wheatRoot, state) {
  const statePath = path.join(wheatRoot, "sync-state.json");
  fs.mkdirSync(path.dirname(statePath), { recursive: true });
  fs.writeFileSync(statePath, `${JSON.stringify(state, null, 2)}\n`, "utf8");
}

// ── Content hash ────────────────────────────────────────────────────────────

/**
 * Compute a SHA-256 hash of a string. Used to detect changes since last sync.
 */
export function contentHash(content) {
  return crypto.createHash("sha256").update(content, "utf8").digest("hex");
}

// ── Confluence storage format builders ──────────────────────────────────────

/**
 * Escape HTML entities for safe embedding in Confluence storage format (XHTML).
 */
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Build a status badge in Confluence storage format.
 */
function statusBadge(status) {
  const colors = {
    active: "Green",
    superseded: "Grey",
    conflicted: "Red",
    resolved: "Blue",
  };
  const color = colors[status] || "Grey";
  return `<ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">${color}</ac:parameter><ac:parameter ac:name="title">${escapeHtml(status)}</ac:parameter></ac:structured-macro>`;
}

/**
 * Build evidence tier badge.
 */
function evidenceBadge(tier) {
  const colors = {
    stated: "Grey",
    web: "Blue",
    documented: "Green",
    tested: "Purple",
    production: "Green",
  };
  const color = colors[tier] || "Grey";
  return `<ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">${color}</ac:parameter><ac:parameter ac:name="title">${escapeHtml(tier)}</ac:parameter></ac:structured-macro>`;
}

/**
 * Build the human-readable claims table in Confluence storage format (XHTML).
 */
export function buildClaimsTable(claims) {
  if (!claims || claims.length === 0) {
    return "<p><em>No claims in this sprint.</em></p>";
  }

  let html = "";
  // Auto-generated banner
  html += '<ac:structured-macro ac:name="info"><ac:rich-text-body>';
  html += "<p>This page is auto-generated by Grainulator <code>/sync</code>. ";
  html +=
    "Do not edit the rendered section -- edits will be overwritten on next sync. ";
  html +=
    "The JSON code block at the bottom is the machine-readable source.</p>";
  html += "</ac:rich-text-body></ac:structured-macro>\n";

  html += "<table><thead><tr>";
  html += "<th>ID</th><th>Type</th><th>Topic</th><th>Status</th>";
  html += "<th>Evidence</th><th>Content</th>";
  html += "</tr></thead><tbody>\n";

  for (const claim of claims) {
    html += "<tr>";
    html += `<td><code>${escapeHtml(claim.id)}</code></td>`;
    html += `<td>${escapeHtml(claim.type)}</td>`;
    html += `<td>${escapeHtml(claim.topic)}</td>`;
    html += `<td>${statusBadge(claim.status)}</td>`;
    html += `<td>${evidenceBadge(claim.evidence)}</td>`;
    html += `<td>${escapeHtml(claim.content)}</td>`;
    html += "</tr>\n";
  }

  html += "</tbody></table>";
  return html;
}

/**
 * Build a collapsed JSON code block in Confluence storage format.
 * This is the machine-readable payload used for backfill/roundtrip.
 */
export function buildJsonCodeBlock(data) {
  const jsonStr = JSON.stringify(data, null, 2);
  let html = '<ac:structured-macro ac:name="expand">';
  html +=
    '<ac:parameter ac:name="title">Machine-readable JSON (do not edit)</ac:parameter>';
  html += "<ac:rich-text-body>";
  html += '<ac:structured-macro ac:name="code">';
  html += '<ac:parameter ac:name="language">json</ac:parameter>';
  html += `<ac:plain-text-body><![CDATA[${jsonStr}]]></ac:plain-text-body>`;
  html += "</ac:structured-macro>";
  html += "</ac:rich-text-body>";
  html += "</ac:structured-macro>";
  return html;
}

/**
 * Build the sync-age banner showing when the page was last synced.
 */
export function buildSyncBanner(timestamp) {
  const isoTime = new Date(timestamp).toISOString();
  return `<ac:structured-macro ac:name="note"><ac:rich-text-body><p>Last synced: ${escapeHtml(isoTime)}</p></ac:rich-text-body></ac:structured-macro>\n`;
}

/**
 * Build the full claims page body: banner + table + JSON block.
 */
export function buildClaimsPageBody(claims, claimsJson, syncTimestamp) {
  let body = "";
  body += buildSyncBanner(syncTimestamp);
  body += buildClaimsTable(claims);
  body += "\n";
  body += buildJsonCodeBlock(claimsJson);
  return body;
}

/**
 * Build the brief page body from compilation.json output.
 */
export function buildBriefPageBody(compilation, syncTimestamp) {
  let body = "";
  body += buildSyncBanner(syncTimestamp);

  if (compilation.brief) {
    body += `<h2>Brief</h2>\n<p>${escapeHtml(compilation.brief)}</p>\n`;
  }

  if (compilation.summary) {
    body += `<h2>Summary</h2>\n<p>${escapeHtml(compilation.summary)}</p>\n`;
  }

  if (compilation.warnings && compilation.warnings.length > 0) {
    body += "<h2>Warnings</h2>\n<ul>\n";
    for (const w of compilation.warnings) {
      body += `<li>${escapeHtml(w)}</li>\n`;
    }
    body += "</ul>\n";
  }

  body += "\n";
  body += buildJsonCodeBlock(compilation);
  return body;
}

// ── MCP tool call builders ──────────────────────────────────────────────────

/**
 * Build the MCP tool call descriptor to create a Confluence page.
 */
export function mcpCreatePage({ spaceKey, title, body, parentPageId, labels }) {
  return {
    tool: "mcp__claude_ai_Atlassian__createConfluencePage",
    params: {
      spaceKey,
      title,
      body,
      ...(parentPageId ? { parentPageId } : {}),
      ...(labels ? { labels: labels.join(",") } : {}),
    },
  };
}

/**
 * Build the MCP tool call descriptor to update a Confluence page.
 */
export function mcpUpdatePage({ pageId, title, body, version }) {
  return {
    tool: "mcp__claude_ai_Atlassian__updateConfluencePage",
    params: {
      pageId,
      title,
      body,
      version,
    },
  };
}

/**
 * Build the MCP tool call descriptor to search for existing sprint pages.
 */
export function mcpSearchPages({ spaceKey, label, title }) {
  const cqlParts = [];
  if (spaceKey) cqlParts.push(`space = "${spaceKey}"`);
  if (label) cqlParts.push(`label = "${label}"`);
  if (title) cqlParts.push(`title = "${title}"`);
  return {
    tool: "mcp__claude_ai_Atlassian__searchConfluenceUsingCql",
    params: {
      cql: cqlParts.join(" AND "),
    },
  };
}

// ── Sync orchestration ──────────────────────────────────────────────────────

/**
 * Plan a sync operation. Reads local state and returns a sync plan
 * describing what MCP calls need to be made.
 *
 * @param {object} opts
 * @param {string} opts.wheatRoot - Path to .wheat directory
 * @param {string} opts.sprintSlug - Sprint slug
 * @param {string} opts.spaceKey - Confluence space key
 * @param {string} [opts.parentPageId] - Optional parent page ID
 * @param {boolean} [opts.archive] - If true, swap labels to wheat-archived
 * @returns {object} Sync plan with page descriptors and MCP call list
 */
export function planSync({
  wheatRoot,
  sprintSlug,
  spaceKey,
  parentPageId,
  archive = false,
}) {
  const sprintDir = path.join(wheatRoot, "sprints", sprintSlug);
  const compilationPath = path.join(sprintDir, "compilation.json");
  const claimsPath = path.join(sprintDir, "claims.json");

  if (!fs.existsSync(compilationPath)) {
    throw new Error(
      `No compilation.json found at ${compilationPath}. Run wheat_compile first.`,
    );
  }

  const compilation = JSON.parse(fs.readFileSync(compilationPath, "utf8"));
  const claimsJson = fs.existsSync(claimsPath)
    ? JSON.parse(fs.readFileSync(claimsPath, "utf8"))
    : null;

  const claims = claimsJson ? claimsJson.claims || [] : [];
  const now = Date.now();
  const hash = contentHash(JSON.stringify({ compilation, claimsJson }));

  // Check sync state for skip-if-unchanged
  const syncState = loadSyncState(wheatRoot);
  const sprintState = syncState[sprintSlug] || {};

  const unchanged = sprintState.lastHash === hash;

  const labels = archive ? ["wheat-archived"] : ["wheat-active"];
  const parentTitle = `Wheat: ${sprintSlug}`;
  const claimsTitle = `${sprintSlug} -- Claims`;
  const briefTitle = `${sprintSlug} -- Brief`;

  return {
    sprintSlug,
    spaceKey,
    parentPageId,
    parentTitle,
    claimsTitle,
    briefTitle,
    labels,
    hash,
    unchanged,
    syncTimestamp: now,
    claimsPageBody: buildClaimsPageBody(claims, claimsJson, now),
    briefPageBody: buildBriefPageBody(compilation, now),
    existingState: sprintState,
  };
}

/**
 * Record a completed sync in sync-state.json.
 */
export function recordSync(
  wheatRoot,
  sprintSlug,
  { hash, syncTimestamp, pages },
) {
  const syncState = loadSyncState(wheatRoot);
  syncState[sprintSlug] = {
    lastHash: hash,
    lastSyncTimestamp: syncTimestamp,
    pages: pages || {},
  };
  saveSyncState(wheatRoot, syncState);
}
