import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { importSession } from '../site/research/session.js';
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined });
const results = [];
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/research/capabilities', route => route.fulfill({ json: { available: true, credentials: {} } }));
  await page.route('**/api/research/models', route => route.fulfill({ json: { models: [{ id: 'anthropic/claude-fable-5.1', name: 'Fable' }] } }));
  await page.route('**/api/research/pass', route => {
    const req = route.request().postDataJSON(); requests.push(req);
    const text = `Pass ${requests.length}: Verify the cache isolation. café 🔎`;
    return route.fulfill({ contentType: 'application/x-ndjson', body: JSON.stringify({ type: 'delta', text }) + '\n' + JSON.stringify({ type: 'result', result: { text, model: req.config.model, sources: [{ title: 'Provider source', url: 'https://example.org/evidence' }], usage: { inputTokens: 30, outputTokens: 40 } } }) + '\n' });
  });
  await page.goto('http://127.0.0.1:4517/playground');
  await page.getByText('Connected to your local research server.', { exact: false }).waitFor();
  assert.equal(await page.locator('canvas').count(), 0);
  assert.equal(await page.locator('header nav a').getAttribute('href'), '/');
  await page.locator('#question').fill('Should we migrate the shared cache?');
  await page.locator('#context').fill('Full context ' + 'matters '.repeat(60));
  await page.locator('#api-key').fill('openai-test-secret');
  await page.locator('#provider').selectOption('openrouter');
  assert.equal(await page.locator('#api-key').inputValue(), '', 'changing provider must not transfer a key');
  await page.locator('#api-key').fill('router-test-secret');
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#run-status').textContent === 'complete');
  assert.equal(requests.length, 3);
  assert.equal(requests[0].config.model, 'anthropic/claude-fable-5.1');
  assert.equal(requests[0].apiKey, 'router-test-secret');
  assert.ok(requests[1].user.includes('matters '.repeat(60)));
  assert.equal(await page.locator('.source-list a').count(), 3);
  assert.match(await page.locator('#result-content').textContent(), /café 🔎/);
  const downloadEvent = page.waitForEvent('download');
  await page.locator('#export-session').click();
  const download = await downloadEvent;
  const exported = fs.readFileSync(await download.path(), 'utf8');
  assert.ok(!exported.includes('test-secret'));
  const session = importSession(JSON.parse(exported));
  assert.equal(session.steps.length, 3);
  await page.locator('#import-session').setInputFiles({ name: 'session.json', mimeType: 'application/json', buffer: Buffer.from(exported) });
  await page.getByText('Session opened.', { exact: false }).waitFor();
  assert.equal(await page.locator('#api-key').inputValue(), '');
  assert.equal(await page.locator('.pass-result').count(), 3);
  await page.locator('#model').fill('another-model');
  assert.equal(await page.locator('.pass-result').count(), 0, 'edited config must invalidate prior checkpoints');
  // Failed passes preserve completed work and resume without running research again.
  await page.unroute('**/api/research/pass');
  let calls = 0;
  await page.route('**/api/research/pass', route => {
    calls++;
    const event = calls === 2 ? { type: 'error', error: 'Fixture provider failure' } : { type: 'result', result: { text: `Useful result ${calls}`, model: 'another-model' } };
    return route.fulfill({ contentType: 'application/x-ndjson', body: JSON.stringify(event) + '\n' });
  });
  await page.locator('#run').click();
  await page.getByText('Fixture provider failure', { exact: true }).waitFor();
  assert.equal(await page.locator('.pass-result').count(), 1); // failed pass has no empty result panel
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#run-status').textContent === 'complete');
  assert.equal(calls, 4, 'resume should run challenge and synthesis only');
  const partial = { ...session, steps: session.steps.slice(0, 1) };
  await page.locator('#import-session').setInputFiles({ name: 'partial.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(partial)) });
  await page.getByText('Continue research →').waitFor();
  // Fresh means a real reset; rerun is a separate action.
  await page.locator('#api-key').fill('clear-this-key');
  await page.locator('#instructions').fill('Clear these instructions');
  await page.locator('#restart').click();
  for (const id of ['question', 'context', 'instructions', 'api-key', 'base-url']) assert.equal(await page.locator(`#${id}`).inputValue(), '', `reset ${id}`);
  assert.equal(await page.locator('#provider').inputValue(), 'openai');
  assert.equal(await page.locator('#model').inputValue(), 'gpt-6-astra');
  assert.equal(await page.locator('#reasoning').inputValue(), 'low');
  assert.equal(await page.locator('#max-tokens').inputValue(), '8192');
  assert.equal(await page.locator('#timeout').inputValue(), '120');
  assert.equal(await page.locator('#retries').inputValue(), '0');
  assert.equal(await page.locator('[data-status="complete"]').count(), 0);
  assert.equal(await page.locator('#run-error').isVisible(), false);
  assert.equal(await page.evaluate(() => document.activeElement.id), 'question');
  await page.locator('#question').fill('Preserve this when stopping');
  await page.unroute('**/api/research/pass');
  await page.route('**/api/research/pass', async route => {
    await new Promise(resolve => setTimeout(resolve, 300));
    await route.fulfill({ contentType: 'application/x-ndjson', body: JSON.stringify({ type: 'result', result: { text: 'Late response' } }) + '\n' }).catch(() => {});
  });
  await page.locator('#run').click();
  await page.getByText('Waiting for model response', { exact: false }).waitFor();
  await page.locator('#stop').click();
  await page.waitForFunction(() => document.querySelector('#run-status').textContent === 'cancelled');
  assert.equal(await page.locator('#question').inputValue(), 'Preserve this when stopping');
  assert.equal(await page.locator('#setup-fields').isEnabled(), true);
  await page.waitForTimeout(350);
  assert.equal(await page.locator('#run-status').textContent(), 'cancelled', 'late response must not overwrite stopped state');
  await page.locator('#restart').click();
  await page.locator('#sample').click();
  assert.equal(await page.locator('#run').isDisabled(), true, 'sample gate must block synthesis');
  assert.match(await page.locator('#evidence-status').textContent(), /r002/);
  const claimsDownload = page.waitForEvent('download');
  await page.locator('#export-claims').click();
  const claimsFile = await claimsDownload;
  const claims = JSON.parse(fs.readFileSync(await claimsFile.path(), 'utf8'));
  assert.equal(claims.claims[0].evidence, 'stated');
  assert.equal(claims.claims.length, 3);
  await page.locator('#restart').click();
  assert.equal(await page.locator('#evidence-gate').isDisabled(), true);
  await page.locator('#ledger').check();
  await page.locator('#evidence-gate').check();
  await page.locator('#blind-spots').check();
  assert.match(await page.locator('#workflow-summary').textContent(), /5 model passes/);
  await page.locator('#question').fill('Show the feature workflow');
  await page.unroute('**/api/research/pass');
  const featureRequests = [];
  await page.route('**/api/research/pass', route => {
    const req = route.request().postDataJSON(); featureRequests.push(req);
    const text = req.system.includes('Return ONLY JSON') ? JSON.stringify({claims: [{id:'r001',type:'factual',topic:'cache',content:'Isolation holds.',sources:[],conflicts_with:[]}]}) : 'Model pass result';
    return route.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({type:'result',result:{text,model:req.config.model}})+'\n'});
  });
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#run-status').textContent === 'blocked');
  assert.equal(featureRequests.length, 4, 'five-pass workflow must stop before synthesis');
  assert.equal(await page.locator('.pass-result').count(), 4);
  assert.equal(await page.locator('#run').isDisabled(), true);
  const gatedDownload = page.waitForEvent('download');
  await page.locator('#export-session').click();
  const gated = JSON.parse(fs.readFileSync(await (await gatedDownload).path(), 'utf8'));
  assert.equal(gated.config.blindSpots, true); assert.equal(gated.config.evidenceGate, true);
  await page.locator('#evidence-gate').uncheck();
  await page.locator('#run').click();
  await page.waitForFunction(() => document.querySelector('#run-status').textContent === 'complete');
  assert.equal(featureRequests.length, 9, 'gate off permits all five passes');
  await page.locator('#ledger').uncheck();
  assert.equal(await page.locator('#evidence-gate').isChecked(), false);
  assert.equal(await page.locator('#evidence-gate').isDisabled(), true);
  await page.locator('#restart').click();
  await page.locator('#sample').click();
  // Safe formatting: model HTML and javascript links must not execute.
  await page.evaluate(async () => {
    const { renderText } = await import('/research/render-text.js');
    const target = document.createElement('div');
    renderText(target, '# Heading\n- **Evidence**\n<script>window.pwned=true</script>\n[x](javascript:alert(1))');
    if (target.querySelector('script') || target.querySelector('a[href^="javascript:"]') || !target.querySelector('h4') || !target.querySelector('strong')) throw Error('Unsafe or missing formatting');
  });
  for (const width of [320, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `overflow at ${width}`);
    await page.waitForFunction(() => [...document.querySelectorAll('.settings textarea')].filter(el => el.getClientRects().length).every(el => el.scrollHeight <= el.clientHeight + 2));
    const help = page.getByRole('button', { name: 'About build a claims ledger' });
    await help.focus(); await page.keyboard.press('Enter');
    assert.equal(await help.getAttribute('aria-expanded'), 'true');
    assert.equal(await page.locator('#ledger-help').isVisible(), true);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `help overflow at ${width}`);
    await page.keyboard.press('Escape');
    assert.equal(await help.getAttribute('aria-expanded'), 'false');
    assert.equal(await page.evaluate(() => document.activeElement.getAttribute('aria-label')), 'About build a claims ledger');
    await page.evaluate(() => scrollTo(0, 0));
    fs.mkdirSync('.dogfood/screenshots', { recursive: true });
    await page.screenshot({ path: `.dogfood/screenshots/playground-${width}.png`, fullPage: true });
    results.push({ width, overflow: false });
  }
  await page.locator('#context').fill('Long context that must remain visible. '.repeat(35));
  await page.waitForFunction(() => { const el = document.querySelector('#context'); return el.scrollHeight <= el.clientHeight + 2; });
  assert.ok(await page.locator('#context').evaluate(el => el.clientHeight > 150));
  const playgroundWidth = await page.locator('.page-shell').evaluate(el => el.getBoundingClientRect().width);
  assert.equal(await page.locator('header img').evaluate(el => el.naturalWidth > 0), true);
  await page.locator('header nav a').click();
  await page.locator('#page-title').waitFor();
  const homepageWidth = await page.locator('.page-shell').evaluate(el => el.getBoundingClientRect().width);
  assert.equal(homepageWidth, playgroundWidth, 'homepage and playground must share a shell width');
  await page.goto('http://127.0.0.1:4517/privacy.html');
  assert.equal(await page.locator('.page-shell').evaluate(el => el.getBoundingClientRect().width), homepageWidth);
  assert.equal(await page.locator('header img').evaluate(el => el.naturalWidth > 0), true);
  for (const width of [320, 768, 1024, 1440]) {
    await page.setViewportSize({width, height:1000});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `privacy overflow at ${width}`);
    await page.screenshot({path: `.dogfood/screenshots/privacy-${width}.png`,fullPage:true});
  }
  await page.locator('aside a[href="#keys"]').focus(); await page.keyboard.press('Enter');
  assert.equal(new URL(page.url()).hash, '#keys');
  await page.goto('http://127.0.0.1:4517/playground');
  // Missing server still permits configuration export, without pretending to run a model.
  await page.route('**/api/research/capabilities', route => route.fulfill({ status: 404 }));
  await page.reload();
  await page.getByText('Configure here. Run on your machine.', { exact: false }).waitFor();
  assert.equal(await page.locator('#run').isDisabled(), true);
  assert.equal(await page.locator('#export-session').isEnabled(), true);
  assert.deepEqual(errors, []);
} finally { await browser.close(); }
fs.writeFileSync('.dogfood/playground-results.json', JSON.stringify({ results, checks: ['provider/model selection', 'credentials excluded from export', 'provider-key isolation', 'UTF-8', 'citations', 'reimport', 'config invalidation', 'partial resume', 'clean URL and home navigation', 'static background', 'fresh reset', 'stop before first text', 'late response isolation', 'safe formatted output', 'mascot', 'consistent page widths', 'textarea growth and unclipped helper text', 'unavailable-server handling', 'feature toggles affect real pass order', 'blocking evidence gate', 'claims download', 'keyboard feature help', 'responsive privacy page'] }, null, 2));
console.log('PASS: configurable playground, safe exports, resumable passes, and four responsive widths.');
