import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile, COMPILER_VERSION, generateCertificate } from '../packages/evidence/compiler/wheat-compiler.js';
import { guard } from '../packages/evidence/lib/guard.js';

// An executable reproduction of the stale-evidence regression, not a model benchmark.
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'grainulator-handoff-'));
const claimsFile = path.join(directory, 'claims.json');
const compilationFile = path.join(directory, 'compilation.json');
const request = JSON.stringify({ tool_input: { file_path: path.join(directory, 'output/release-brief.md') } });
const initial = {
  schema_version: '1.0',
  meta: { question: 'Is the release brief based on the current evidence?', phase: 'research' },
  claims: [{ id: 'release-check', type: 'factual', topic: 'release', content: 'The migration regression check passed.', evidence: 'tested', status: 'active', source: 'Synthetic release-check fixture' }],
};
const stages = [];
function capture(id, title, explanation) {
  const claims = JSON.parse(fs.readFileSync(claimsFile, 'utf8'));
  const compilation = JSON.parse(fs.readFileSync(compilationFile, 'utf8'));
  const decision = guard(directory, request);
  stages.push({ id, title, explanation, claim: claims.claims[0].content, decision,
    inputHash: generateCertificate(claims).input_hash,
    compiledHash: compilation.compilation_certificate.input_hash,
    compilationStatus: compilation.status });
  return decision;
}
try {
  fs.writeFileSync(claimsFile, JSON.stringify(initial, null, 2));
  compile(claimsFile, compilationFile, directory, { skipSprintDetection: true });
  assert.equal(capture('checked', 'The handoff is checked', 'The compiler records which evidence it checked. The output guard allows the brief because that evidence still matches.').allow, true);
  const stat = fs.statSync(claimsFile);
  const changed = JSON.parse(fs.readFileSync(claimsFile, 'utf8'));
  changed.claims[0].content = 'The migration regression check failed after the latest change.';
  fs.writeFileSync(claimsFile, JSON.stringify(changed, null, 2));
  fs.utimesSync(claimsFile, stat.atime, stat.mtime);
  assert.equal(capture('changed', 'The evidence changes', 'A later check fails. The file timestamp is preserved, reproducing the old bug. The new guard checks the content and blocks the stale handoff.').allow, false);
  compile(claimsFile, compilationFile, directory, { skipSprintDetection: true });
  assert.equal(capture('rechecked', 'The brief can reflect the failure', 'Recompiling binds the brief to the changed evidence. This permits writing an accurate brief; it does not approve the release or make the failed check pass.').allow, true);
  const artifact = {
    schema: 'grainulator.handoff-example.v1', recordedAt: new Date().toISOString(), compilerVersion: COMPILER_VERSION,
    provenance: 'Generated by scripts/record-handoff.mjs using the local evidence compiler and output guard. Synthetic release claims; real compiler and guard results. No model was called, no brief was written, and no release was published.',
    reproduction: 'node scripts/record-handoff.mjs',
    scope: 'The guard validates compilation freshness for an output path when the host invokes it. It does not verify the truth of claims or enforce a release gate on its own.',
    stages,
  };
  const destination = fileURLToPath(new URL('../site/handoff-trace.json', import.meta.url));
  fs.writeFileSync(destination, JSON.stringify(artifact, null, '\t') + '\n');
  console.log('Recorded three real guard decisions: allow → block → allow. Assertions passed.');
} finally {
  fs.rmSync(directory, { recursive: true, force: true });
}
